# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moringa_main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='globaladmin',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='localadmin',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='userId',
            new_name='user',
        ),
    ]
