# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moringa_main_app', '0002_auto_20171119_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localadmin',
            name='location',
            field=models.CharField(choices=[('nairobi', 'NAIROBI, KENYA'), ('mumbai', 'MUMBAI, INDIA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='localadmin',
            name='program',
            field=models.CharField(choices=[('prep', 'MORINGA PREP'), ('core', 'MORINGA CORE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='cohort',
            field=models.CharField(choices=[('1', 'COHORT 1'), ('2', 'COHORT 2'), ('3', 'COHORT 3'), ('4', 'COHORT 4'), ('5', 'COHORT 5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='students',
            name='location',
            field=models.CharField(choices=[('nairobi', 'NAIROBI, KENYA'), ('mumbai', 'MUMBAI, INDIA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='program',
            field=models.CharField(choices=[('prep', 'MORINGA PREP'), ('core', 'MORINGA CORE')], max_length=10),
        ),
    ]
