# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 07:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moringa_main_app', '0005_auto_20171203_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ip_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
